name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: krkr
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: krkr/ktty
          flavor: latest=true
          tags: type=sha,prefix=
      
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}